SUBE AL GITHUB
(11:33:22 a.m.) SELECT (ROW_NUMBER() OVER(ORDER BY ACODIGO))AS ITEM,ACODIGO,ADESCRI,AFAMILIA,AUNIDAD,STSKDIS=ISNULL(STSKDIS,0),
ISNULL(CANT_PEND,0)AS CANT_RESEV,
(ISNULL(STSKDIS,0)-ISNULL(CANT_PEND,0))AS CANT_DISP,ACOMENTA, 
[Control de Stock]= case 
when AFSERIE='N' and AFLOTE='N' and AFSTOCK='N' then 'Servicio'
when  AFSTOCK='S' then 'Libre'
when AFSERIE='S'  then 'Stock x serie'
when  AFLOTE='S'  then 'Stock x Lote'
else '' end
FROM [011BDCOMUN].DBO.MAEART AS M 
LEFT JOIN (SELECT STCODIGO,STSKDIS FROM  [011BDCOMUN].DBO.STKART WHERE STALMA='01') AS S ON M.ACODIGO=S.STCODIGO  AND AFAMILIA='SERV'  AND AESTADO='V'
LEFT JOIN (SELECT CODIGO,CANT_PEND=SUM(CANT_PEND) FROM [020BDCOMUN].DBO.RESERVA_DET GROUP BY CODIGO) AS D ON S.STCODIGO=D.CODIGO 
WHERE  AESTADO='V' AND ACODIGO IN ('0147148103','020511-375')
--SOLO ARTICULOS LIBRES
/*AND AFSTOCK='S'*/