SELECT CODIGOOT"OT",CODIGOCENTROCOSTO"CENTRO DE COSTO",CC.CODIGO"CODIGO ARTICULO",M.ADESCRI"DESCRIPCION ARTICULO",M.AUNIDAD"UND",O.OF_ARTCANT"CANTIDAD OT",
ISNULL(NI.CANT,0.00)"CANTIDAD NI",ISNULL(S.STSKDIS,0.00)AS STOCK,
O.OF_FECHINI"FECHA DE INICIO",O.OF_FECHFIN"FECHA DE FIN",CC.PRIORIDAD,O.OF_ARTNOM"DESCRIPCION OT",O.OF_CLINOM"CLIENTE",
CASE ISNULL(NI.CANT,0.00)-O.OF_ARTCANT
WHEN 0  THEN 'POR LIQUIDAR'
ELSE
'PENDIENTE' 
END AS ESTADO
FROM [022BDCOMUN].DBO.CENCOSOT AS CC INNER JOIN [010BDCOMUN].DBO.ORD_FAB AS O ON CC.CODIGOOT=O.OF_COD
LEFT JOIN(
SELECT OT AS FN_OT,MIN(FECHA_ENTREGA) AS FN_FECHA_ENTREGA FROM [010BDAPLICACION].DBO.PEDDET 
GROUP BY OT
)AS FN ON CC.CODIGOOT=FN.FN_OT
LEFT JOIN [010BDCOMUN].DBO.MAEART AS M ON CC.CODIGO=M.ACODIGO
LEFT JOIN [010BDCOMUN].DBO.STKART AS S ON CC.CODIGO=S.STCODIGO AND STALMA='01'
	LEFT JOIN (SELECT c.CARFNDOC,CANT= SUM(D.DECANTID) 
	FROM [010BDCOMUN].dbo.MOVALMCAB AS C INNER JOIN [010BDCOMUN].dbo.MOVALMDET AS D ON C.CANUMDOC=D.DENUMDOC 
	WHERE C.CAALMA=D.DEALMA AND C.CAALMA='01' AND C.CACODMOV IN ('IP','IE') AND C.CATD=D.DETD and c.CARFTDOC='OF'
	group by C.CARFNDOC) AS NI ON CC.CODIGOOT=NI.CARFNDOC
WHERE CODIGOOT IN (SELECT OF_COD FROM [010BDCOMUN].dbo.ORD_FAB WHERE OF_ESTADO ='ACTIVO') /*AND CARFNDOC='F9620'*/
ORDER BY CAST(SUBSTRING(O.OF_COD,2,20) AS INT)