---pedido guia factura

SELECT  CFNUMPED,CFFECDOC,CFCODCLI,CFNOMBRE,
DFSECUEN,DFCODIGO,DFDESCRI,DFUNIDAD,DFCANTID,DFSALDO,
CATD,CACODMOV,CANUMDOC,CAFECDOC,deitem,DECODIGO,DECANTID 
from PEDDET inner join PEDCAB on CFNUMPED=DFNUMPED
inner join maeart on DFCODIGO=ACODIGO and AFSTOCK='S'
LEFT JOIN 
(select CATD,CACODMOV,CANROPED,CANUMDOC,CAFECDOC,DEITEM,DECODIGO,DECANTID 
from MOVALMDET inner join MOVALMCAB on DENUMDOC=CANUMDOC
where   DECODIGO !='TEXTO') AS M ON CFNUMPED=M.CANROPED AND DFCODIGO=M.DECODIGO
where DFCODIGO !='TEXTO' AND CFFECDOC BETWEEN '25-08-2016' AND '30-09-2016'--and DFNUMPED='0008365'
ORDER BY CFNUMPED,DFSECUEN,DEITEM